export const books = [
    {
      id: 1,
      title: "The Bird With Golden Wings",
      author: "Sudha Murthy",
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book3.jpeg'),
    },
    {
      id: 2,
      title: " the Adventures of Pinnocchio",
      author: "Steve Krug", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book5.jpeg'),
    },
    {
      id: 3,
      title: "The Law of Garbage Truck",
      author: "Mark Twain", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book3.jpeg'),
    },
    
    {
      id: 4,
      title: "The Story of Magical Temple",
      author: "Sudha Murthy", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book3.jpeg'),
    },
    {
      id: 5,
      title: "Chacha Choudhary",
      author: "Steve Krug", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book3.jpeg'),
    },
    {
      id: 6,
      title: "Chacha Choudhary",
      author: "Steve Krug", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book5.jpeg'),
    },
    {
      id: 7,
      title: "Chacha Choudhary",
      author: "Steve Krug", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book5.jpeg'),
    },
    {
      id: 8,
      title: "Chacha Choudhary",
      author: "Steve Krug", 
      currentPrice: 1500,
      originalPrice: 2000,
      image: require('../../assets/images/book5.jpeg'),
    },
  ];